[metadata]
creation_date = "2020/09/03"
ecs_version = ["1.6.0"]
maturity = "development"
updated_date = "2020/09/03"

[rule]
anomaly_threshold = 25
author = ["randomuserid"]
description = "description"
false_positives = ["false positives"]
from = "now-45m"
interval = "15m"
license = "Elastic License"
machine_learning_job_id = "linux_rare_kernel_module_arguments"
name = "Anomalous Kernel Module Activity"
note = "investigation notes"
references = ["references"]
risk_score = 21
rule_id = "37b0816d-af40-40b4-885f-bb162b3c88a9"
severity = "low"
tags = ["Elastic", "Linux", "ML"]
type = "machine_learning"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1215"
name = "Kernel Modules and Extensions"
reference = "https://attack.mitre.org/techniques/T1215/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

