[metadata]
creation_date = "2020/08/24"
ecs_version = ["1.5.0"]
maturity = "production"
updated_date = "2020/08/24"

[rule]
author = ["Elastic"]
description = """
A suspicious WerFault instance command line was detected, which may indicate an attempt to run unnoticed. Verify
process details such as command line, network connections, file writes and parent process details as well.
"""
false_positives = ["Legit Application Crash with rare Werfault commandline value"]
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Potential Process Masquerading as WerFault"
references = [
    "https://twitter.com/SBousseaden/status/1235533224337641473",
    "https://www.hexacorn.com/blog/2019/09/20/werfault-command-line-switches-v0-1/",
]
risk_score = 47
rule_id = "6ea41894-66c3-4df7-ad6b-2c5074eb3df8"
severity = "medium"
tags = ["Elastic", "Windows"]
type = "query"

query = '''
event.category:process and not event.type:end and
 process.name:WerFault.exe  and
 not process.args:((("-u" or "-pss") and "-p" and "-s") or ("/h" and "/shared") or ("-k" and "-lcq"))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
