[metadata]
creation_date = "2020/08/14"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/08/14"

[rule]
author = ["Elastic"]
description = """
Identifies execution via MSSQL xp_cmdshell stored procedure. Because malicious users sometimes attempt to elevate their
privileges by using xp_cmdshell, xp_cmdshell is disabled by default. Thus it's important to review the context of it's
use.
"""
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Execution via MSSQL xp_cmdshell stored procedure"
risk_score = 73
rule_id = "4ed493fc-d637-4a36-80ff-ac84937e5461"
severity = "high"
tags = ["Elastic", "Windows"]
type = "query"

query = '''
event.category:process and not event.type:end and
  process.name:cmd.exe and
  process.parent.name:sqlservr.exe
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command-Line Interface"
reference = "https://attack.mitre.org/techniques/T1059/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
