[metadata]
creation_date = "2020/08/13"
ecs_version = ["1.5.0"]
maturity = "production"
updated_date = "2020/08/13"

[rule]
author = ["Elastic"]
description = """
Detects creation of new Group Policy based Scheduled Task or Service. Both methods are used for legit system
administration but can be abused by an attacker with domain admin level to execute a malicious payload remotely on all
or a subset of the domain joined machines.
"""
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Creation of a new GPO Scheduled Task or Service"
risk_score = 21
rule_id = "c0429aa8-9974-42da-bfb6-53a0a515a145"
severity = "low"
tags = ["Elastic", "Windows"]
type = "query"

query = '''
event.category:file and not event.type:deletion and
  file.path:(C\:\\Windows\\SYSVOL\\domain\\Policies\\*\\Machine\\Preferences\\ScheduledTasks\\ScheduledTasks.xml or
             C\:\\Windows\\SYSVOL\\domain\\Policies\\*\\Machine\\Preferences\\Services\\Services.xml) and
  not process.name:dfsrs.exe
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1053"
name = "Scheduled Task"
reference = "https://attack.mitre.org/techniques/T1053/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

